[project]
name = "libtrack"
version = "1.0.0"
description = "Online library tracking software developed using Flask."
dependencies = [
    "flask",
    "requests"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"