[project]
name = "libtrack"
version = "1.0.0"
description = "Library tracking software built using Flask."
dependencies = [
    "flask",
    "requests",
    "waitress"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"